compressionLevel: mixed
nodeLinker: node-modules
npmRegistryServer: "https://npm.pkg.github.com"

npmScopes:
  digital-alchemy:
    npmAlwaysAuth: true
    npmRegistryServer: "https://npm.pkg.github.com"
    npmAuthToken: "${NODE_AUTH_TOKEN}"
