version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - astro
  - bithound
  - buildable
  - caseta
  - cbar
  - codeowners
  - codez
  - creationrc
  - Datetime
  - dbaeumer
  - devkit
  - dhall
  - entites
  - esbenp
  - execa
  - exiasr
  - falsey
  - fastify
  - Gbit
  - gotify
  - gridsome
  - hadolint
  - hass
  - hassio
  - homeassistant
  - idris
  - intellij
  - interwebs
  - julianday
  - kbit
  - KEYFILE
  - keylist
  - kusto
  - lifecycles
  - Lutron
  - managerrc
  - mbar
  - Mbit
  - mireds
  - mrad
  - nrwl
  - nsoult
  - nxignore
  - Pico
  - pino
  - pkief
  - postdata
  - prettyrc
  - proto
  - purescript
  - reftimes
  - shellcheck
  - sinm
  - sinonjs
  - sonarjs
  - terminalizer
  - testrc
  - timonwong
  - toolbelt
  - tsdoc
  - typeof
  - undici
  - unitless
  - visbility
  - vsix
  - womp
  - zipignore
ignoreWords: []
import: []
