version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - toolbelt
  - nrwl
  - devkit
  - sinonjs
  - pino
  - hass
  - prettyrc
  - testrc
  - creationrc
  - managerrc
  - testrc
  - creationrc
  - prettyrc
  - managerrc
  - vsix
  - terminalizer
  - buildable
  - sonarjs
  - pkief
  - postdata
  - dbaeumer
  - execa
  - purescript
  - idris
  - undici
  - proto
  - keylist
  - exiasr
  - hadolint
  - homeassistant
  - lifecycles
  - esbenp
  - typeof
  - gridsome
  - nsoult
  - kusto
  - nxignore
  - visbility
  - timonwong
  - shellcheck
  - bithound
  - dhall
  - gotify
  - intellij
ignoreWords: []
import: []
