create_entity:
  description: Creates a new virtual entity.
  fields:
    entity_id:
      description: The entity ID for the new entity.
      example: "zcc.custom_switch"
    friendly_name:
      description: A friendly name for the entity.
      example: "My Custom Switch"
    icon:
      description: The icon to use for the entity.
      example: "mdi:toggle-switch"

update_entity:
  description: Updates an existing virtual entity.
  fields:
    entity_id:
      description: The entity ID of the entity to update.
      example: "zcc.custom_switch"
    state:
      description: The new state for the entity.
      example: "on"
    attributes:
      description: A dictionary of new attributes to apply to the entity.
      example: {"friendly_name": "Updated Name", "icon": "mdi:new-icon"}

remove_entity:
  description: Removes an existing virtual entity.
  fields:
    entity_id:
      description: The entity ID of the entity to remove.
      example: "zcc.custom_switch"
