---
services:
  homeassistant:
    container_name: digital_alchemy_home_assistant
    image: homeassistant/home-assistant:2024.1
    network_mode: "host"
    volumes:
      - ./config:/config
    restart: unless-stopped
