name: Dependabot auto-merge
on: pull_request

permissions:
  contents: write
  pull-requests: write
  statuses: read

jobs:
  code_check:
    name: 🔬 PR Checks
    uses: ./.github/workflows/check.yml
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  dependabot:
    runs-on: ubuntu-latest
    needs: code_check
    if: github.event.pull_request.user.login == 'dependabot[bot]'
    steps:
      - name: Wait for checks to pass
        uses: fountainhead/action-wait-for-check@v1.2.0
        id: wait-for-check
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: lint-and-build
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@08eff52bf64351f401fb50d4972fa95b9f2c2d1b
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Enable auto-merge for Dependabot PRs
        if: steps.wait-for-check.outputs.conclusion == 'success'
        run: gh pr merge --auto --squash --delete-branch "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
