name: Publish to GitHub Package Registry

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  packages: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '22'
    - run: corepack enable
    - run: yarn config set enableImmutableInstalls false
    - run: yarn
    - run: yarn build
    - run: yarn lint
    - run: yarn test
    - name: Configure package.json for GitHub Packages
      run: |
        # Get git short hash
        GIT_HASH=$(git rev-parse --short HEAD)
        # Append hash to version
        jq --arg hash "$GIT_HASH" '.version = .version + "-" + $hash' package.json > package.json.tmp && mv package.json.tmp package.json
        # Set registry
        jq '.publishConfig = {"registry": "https://npm.pkg.github.com"}' package.json > package.json.tmp && mv package.json.tmp package.json
        cp .yarnrc.github.yml .yarnrc.yml
    - name: Publish to GitHub Package Registry
      run: yarn npm publish --scope digital-alchemy-ts
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
